'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Teacher

    '''<summary>
    '''ddlTopics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTopics As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rqdfddltopic control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqdfddltopic As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtStartDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStartDateTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cusStartDateTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusStartDateTime As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ddlHours control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHours As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlMinutes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMinutes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CusValDuration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CusValDuration As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''ddlTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTimeZone As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rqfvddlTimeZone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rqfvddlTimeZone As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''BtnCreateTest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreateTest As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dvmessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dvmessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hdnlocaltimezone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnlocaltimezone As Global.System.Web.UI.WebControls.HiddenField
End Class
